query Torrents($orderBy: [TorrentOrderByWithRelationInput!]) {
  torrents(orderBy: $orderBy, take: 5 ) {
    torrentId
    name
    size
    progress
    addedAt
  }
}

# subscription TorrentsUpdates {
#   torrentsUpdate {
#     torrentId
#     downloaded
#     ratio
#     eta
#   }
# }
