query Torrents($orderBy: [TorrentOrderByWithRelationAndSearchRelevanceInput!], $where: TorrentWhereInput) {
  torrents(orderBy: $orderBy, where: $where, take: 10 ) {
    torrentId
    name
    size
    progress
    addedAt
  }
}

# subscription TorrentsUpdates {
#   torrentsUpdate {
#     torrentId
#     downloaded
#     ratio
#     eta
#   }
# }
