name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: droplt/app:latest
  # deploy:
  #   name: Deploy webhook call
  #   runs-on: ubuntu-18.04
  #   needs: [docker]
  #   steps:
  #     - name: Deploy docker container webhook
  #       uses: joelwmale/webhook-action@master
  #       env:
  #         WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
  #         data: "{ 'myField': 'myFieldValue'}"
