name: ci

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  deploy-production:
    if: ${{ env.GITHUB_REF_NAME }} == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      imageName: droplt/app:stable
      deployScript: ./deploy-app.sh
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
      sshHost: ${{ secrets.SSH_HOST }}
      sshPort: ${{ secrets.SSH_PORT }}
      sshUsername: ${{ secrets.SSH_USERNAME }}
      sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      sshPrivateKeyPassphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
  deploy-staging:
    if: ${{ env.GITHUB_REF_NAME }} == 'develop'
    uses: ./.github/workflows/deploy.yml
    with:
      imageName: droplt/app:staging
      deployScript: ./deploy-app-staging.sh
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
      sshHost: ${{ secrets.SSH_HOST }}
      sshPort: ${{ secrets.SSH_PORT }}
      sshUsername: ${{ secrets.SSH_USERNAME }}
      sshPrivateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      sshPrivateKeyPassphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
